# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skipass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=19)),
                ('price', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time_from', models.CharField(max_length=10)),
                ('time_to', models.CharField(max_length=10)),
            ],
        ),
    ]
